discord:
  discordSRV: true
  leaderRole: "995382001500692571"
  gameToDiscordFormat: "%player%: %message%"
  discordToGameFormat: "[D] %name%: %message%"
  maxClanNameLength: 16
  maxClanTagLength: 16
  clanChat:
    categoryID: "995375231801765978"
clan:
  protection:
    maxHomes: 1
    homeTeleportCD: 5
economy:
  discordChannelPurchaseAmount: 0
  discordLeaderRolePurchaseAmount: 0
  clanCreatePurchaseAmount: 0
  clanInvitePurchaseAmount: 0
  clanJoinPurchaseAmount: 0
  clanHomeCreatePurchaseAmount: 0
  clanHomeTeleportPurchaseAmount: 0
