package com.astrainteractive.astraclans.domain.dto

enum class FlagsEnum {
    BLOCK_BREAK_DENY,
    BLOCK_PLACE_DENY,
    BLOCK_IGNITE_DENY,
    CREATURE_SPAWN_DENY,
    GROW_DENY,
    EXPLODE_DENY,
    PISTON_DENY,
    BLOCK_DAMAGE_DENY,
    BLOCK_INTERACT_DENY,
    BLOCK_FORM_DENY,
    BLOCK_FERTILIZE_EVENT_DENY,
    SIGN_CHANGE_DENY,
    BUCKET_EMPTY_DENY,
    BUCKET_FILL_DENY,
    HANGING_PLACE_DENY,
    HANGING_BREAK_DENY,
    PVP
}